set -a terminal-features "tmux-256color:RGB"
set -g prefix C-SPACE
set -g base-index 1
set -g renumber-windows on
set -g mode-keys vi
set -g status-position top
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g window-status-current-style "fg=black bg=white  "
set -g window-status-current-style "fg=colour255,bg=default,bold"
set -g window-status-separator "  "
set -g window-status-format "#I:#W#{?window_flags,#{window_flags},}"
set -g window-status-current-format "#[bold]#I:#W#{?window_flags,#{window_flags},}#[default]"
set -g status-interval 1
set -g status-left "#[fg=colour255]#(basename \"#{pane_current_path}\")"
set -g status-right ""
set -g remain-on-exit "off"

bind r source-file "~/.config/tmux/tmux.conf"
bind b set -g status
bind x kill-window
bind f run "tmux neww ~/.config/tmux/script/tmux-session-dispensary.sh"
#bind H run "~/.config/tmux/script/tmux-session-dispensary.sh ~/.config"
bind g neww -n "git" -S lazygit
